server:
  port: 7777

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aj_blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: waj
  #文件上传
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
#  redis:
#    port: 6379
#    url: 120.78.89.222
#    username: waj172
#    password: waj172
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除的字段
      logic-delete-field: delFlag
      logic-not-delete-value: 0
      logic-delete-value: 1
      # 表前缀
      table-prefix: aj_

